services:
  - type: web
    name: keiba-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    healthCheckPath: /
